umccr/data-portal-client

src/Routes.js
src/containers/Home.js
src/containers/LandingPage.js

* Separated public landing page from home to callback API after authenticated

Added landing page

---

src/App.js
src/actions/home.js
src/containers/AppBar.js
src/containers/Home.js
src/containers/Search.js
src/reducers.js

* Updated columns of interest in home view
* Improved presentation table on search and home view
* Removed search box on home view

Added sortable columns in home view

---

src/components/EnhancedTableHead.js
src/containers/Home.js
src/containers/Search.js
src/reducers.js

* Moved actions out from table head
* Minor refactor code to use camelCase
* Improved header columns

Added search filter in home table view

---

src/containers/Home.js

Removed redundant rn and url fields

---

src/containers/Home.js

* Used react router link for better XHR call

Improved Subject button

---

src/containers/Subject.js

Updated support for extension filter

---

src/actions/subject.js
src/containers/Subject.js

* Improved predefined query filters

Added Snackbar in Subject view to handle API errors

---

src/components/HumanReadableFileSize.js

Fixed human readable to decimal metric

---

src/components/ActionMenuButton.js
src/containers/Subject.js

* Updated default VCF query
* Allowed vcf.gz open in IGV

Improved Open in IGV error handling

---

src/components/ActionMenuButton.js
src/containers/Run.js
src/reducers.js

* Added expandable panel wrap to data tables
* Added QC reports query by default
* Added clickable report links with clicked indication
* Minor UX adjustments

Improved run specific view presentation

---

src/containers/Run.js

* Adjusted Link hover to show cursor pointer

Moved collapsible panel expand icon to left

---

src/components/ActionMenuButton.js
src/containers/Run.js

* Show S3 object status upon actions
* Updated to use new presign endpoint
* Added support for restore t.b.c
* Minor refactor

Added support for Glacier and Restore status

---

src/components/ActionMenuButton.js
src/containers/Run.js
src/containers/Subject.js

* Improved tracking restore status and message prompts
* Updated to POST payload for restore request
* Default to 7 days with Bulk tier

Enabled Glacier Restore

---

package.json
src/App.js
src/components/ActionMenuButton.js
src/containers/Subject.js
src/primeflex.css
src/primeod.css
yarn.lock

* Dashboard panels - Overview, Feature Circos plot, Sample Info, Analysis Results
* Added PrimeReact UI kit for better dashboard presentation
* Added dense view support in ActionMenuButton
* Bumped react-scripts 3.4.1 to fix audit on acorn and minimist

Implemented subject landing view using analysis results

---

src/containers/Run.js
src/containers/Subject.js

* Added last modified date on result table
* Rearranged circos plot along with other results

Added GDS showcase note

---

README.md
src/containers/Subject.js

* Updated filter query for vcf and cpsr pcgr report
* Added `.maf` support for Analysis Panel
* Minor update README

Updated Subject chip filter view query

---

src/containers/Subject.js

* Updated to use Portal data content server endpoint
using AWS v4 signature signed request
* Use Amplify Signer for signing HTTP Request URL
* Signer credentials use Cognito STS assume role
through Amplify Auth component

Implemented AWS v4 signature signed request

---

src/components/GDSActionMenuButton.js
src/containers/Run.js

* Added download actions through GDS PreSigned URL
* Added chip filter support: QC report, FASTQs

Updated Run view to support run results from GDS

---

src/containers/Subject.js

* Avoid serving cacao and circos from `work/` directory
See https://github.com/umccr/data-portal-apis/issues/141

Updated canned queries for umccrise results

---

docker-compose.yml
htsget-config-local.json
src/containers/AppBar.js
src/containers/IGV.js
src/utils/signer.js

* Improved token generation
* Fixed docker compose

Improved IGV load track UX

---

.husky/pre-commit
.huskyrc.json
README.md
package.json
yarn.lock

* Upgraded pre-commit hook from husky v4 to v5

Bumped deps and fixed husky

---

src/actions/run.js
src/actions/runmeta.js
src/actions/subject.js
src/containers/IGV.js

Deprecated nested endpoints

---

package.json
src/containers/Run.js
src/containers/Subject.js
yarn.lock

* Improved GDS text description
* Bumped deps
Fixes #50

Added chip filter for cancer report tables

---

package.json
src/containers/IGV.js
yarn.lock

* Attempt #64 #65 didn't work
* Pinned igv.js 2.7.4 for now

Rolled back igv.js 2.7.4

---

src/components/GDSActionMenuButton.js
src/containers/Subject.js

* Added preliminary GDS query for chip filters

Connected Open in IGV app to files from GDS

---

src/containers/IGV.tsx
src/containers/Run.js

* Improved and minor UI/UX adjustment

Updated IGV Subject data loading with subject endpoint

---

src/components/LaunchPadDialog.js
src/containers/Subject.js

Added pre-launch BAM archive check for GPL Report trigger

---

src/App.js

- Added link to `sscheck` page
- Added link to `status-page` page

Added External Link to Drawer

---

src/components/LaunchPadDialog.js
src/containers/Subject.js

* Related #117 and https://github.com/umccr/data-portal-apis/issues/431

Added confirmation check for GPL Report trigger

---

src/components/PreviewActionButton.tsx
src/containers/FileViewer.tsx
src/containers/Subject.js

- add to support html and png files
- add filter for WTS and WGS
- aligned-center image when open in preview
- Add a maximum fileSize for the `/files` endpoint

Add filetype filters and css fix

---

src/containers/FileViewer.tsx
src/containers/Run.js
src/containers/Subject.js

Related
* https://github.com/umccr/data-portal-apis/pull/462
* https://github.com/umccr/data-portal-apis/issues/457

Added and switched default Subject Analysis Results to GDS

---

package.json
yarn.lock

Bumped version 1.0.0 and dependencies

---

src/components/LaunchRNAsumReport.tsx
src/containers/Subject.js
src/utils/rnasum.js

- Added RNAsum trigger button via portal api `/manops/rnasum` route
- Import list of RNAsum datasets from  [GitHub](https://github.com/umccr/RNAsum/blob/master/TCGA_projects_summary.md#pan-cancer-dataset)

add RNAsum button

---

package.json
src/components/PreviewActionButton.tsx
yarn.lock

- Support  tsv, csv, json, yaml, txt 
- add copy button if data becomes available
Followup:
- enable cors-origin on the primary-data s3 bucket

Enable back FileViewer

---

src/components/DataTableWrapper/index.tsx
src/containers/lims/LIMSTable/index.tsx
src/containers/metadata/MetadataTable/index.css
src/containers/metadata/MetadataTable/index.tsx
src/pages/LIMS/index.tsx
src/pages/metadata/index.tsx
src/routes/index.tsx

- Metadata Page && Lims Page
- Sortable Data Table Wrapper

Metadata and LIMS Page Init

---

src/containers/Subject.js

* Switched from S3 (bcbio) to GDS (DRAGEN) inputs
* Removed archived status check for BAM files
Related:
* https://github.com/umccr/data-portal-apis/pull/490

Update GPL trigger to use GDS (DRAGEN) inputs

---

package.json
src/components/FilePreviewButton/index.tsx
src/components/ViewPresignedUrl/index.css
src/components/ViewPresignedUrl/index.tsx
src/containers/subjects/AnalysisResultTable/index.tsx
src/containers/subjects/GDSSubjectDataTable/index.tsx
src/containers/subjects/S3SubjectDataTable/index.tsx
yarn.lock

Align with V1 release, this PR will also enable back on viewing filetype other than image or html page

Reconfigure File Viewer

---

src/config.js
start.sh

* LINX plotting Lambda is not supported for ICA. See upstream
https://github.com/umccr/gridss-purple-linx-nf/commit/a015146e95e1b7cd3de3bc639cbc600887ba42ff

Disabled LINX plotting Lambda

---

package.json
src/containers/Subject.js
yarn.lock

* Improved label text to tso chip filter

Bumped dependencies

---

package.json
src/components/LaunchRNAsumReport.tsx
src/components/PreviewActionButton.tsx
src/config.js
src/containers/Subject.js
src/utils/rnasum.js
start.sh
yarn.lock

See https://github.com/umccr/data-portal-client/milestone/6?closed=1

Release 1.1.0

---

src/components/DataTableWrapper/index.css
src/components/DataTableWrapper/index.tsx
src/containers/subjects/SampleInformationTable/index.tsx
src/containers/subjects/SubjectGPLLaunch/index.tsx
src/containers/subjects/SubjectRNASumLaunch/index.css
src/containers/subjects/SubjectRNASumLaunch/index.tsx
src/containers/subjects/SubjectRNASumLaunch/utils.ts
src/layouts/Breadcrumbs/index.tsx
src/pages/subjects/SubjectLaunchPad/index.tsx
src/routes/subjects/index.tsx

Implemented LaunchPad page, to allow to trigger RNASum and GPL from the portalV2

Subject LaunchPad Page

---

package.json
src/API/subject.ts
src/containers/subjects/IGV/LoadCustomTrackDataButton.tsx
src/containers/subjects/IGV/LoadSubjectDataButton.tsx
src/containers/subjects/IGV/genomes.ts
src/containers/subjects/IGV/index.tsx
src/containers/subjects/IGV/utils.ts
src/pages/subjects/SubjectIGVPage/index.tsx
src/typings/index.d.ts
yarn.lock

IGV component on subject page
- IGV.js component
- Button to Load IGV.js from gds/s3
- Field to put custom s3key path

Subject IGV Page

---

src/containers/subjects/GDSSubjectDataTable/index.tsx
src/containers/subjects/S3SubjectDataTable/index.tsx
src/containers/subjects/SubjectRNASumLaunch/index.tsx

Seems that some import statements are somehow missing from files. Fixing it in this PR!
Possible that it was missed by git during the merge process. (as the there were multiple merges and the order of merge might not be right).

Fix Import

---

src/api/run.ts
src/containers/gds/GDSDataTable/index.tsx
src/containers/lims/LIMSTable/index.tsx
src/containers/runs/RunOverviewTable/index.tsx
src/containers/runs/RunSideBar/index.tsx
src/containers/s3/S3DataTable/index.tsx
src/layouts/Breadcrumbs/index.tsx
src/layouts/MenuBar/index.tsx
src/layouts/SideBar/index.tsx
src/pages/LIMS/index.tsx
src/pages/runs/RunDataPage/index.tsx
src/pages/runs/RunMetadataPage/index.tsx
src/pages/runs/RunOverviewPage/index.tsx
src/routes/index.tsx
src/routes/runs/index.tsx
src/routes/subjects/index.tsx

- Added `/runs` page
- /runs/{runId}/overview
- /runs/{runId}/metadata
- /runs/{runId}/run-data
- Create S3/GDS table component.
closes #158

Issue #158 - Runs page

---

src/containers/lims/LIMSTable/index.tsx
src/containers/runs/RunSideBar/index.tsx
src/pages/runs/RunLIMSPage/index.tsx
src/routes/runs/index.tsx

- Renaming `Metadata` -> `LIMS` on run page, API used is `/lims` for tables.
- Connecting LIMS table to appropriate `/runs` page

Patch `/runs` page

---

src/containers/subjects/AnalysisResultTable/index.tsx

Found a way to straighten column by specifying fix width to last few columns.

Align fields column in Subject Data Table

---

src/components/DataActionButton/index.tsx
src/components/ViewPresignedUrl/index.tsx
src/containers/gds/GDSDataTable/index.tsx
src/containers/home/LimsCard/index.tsx
src/containers/home/MetadataCard/index.tsx
src/containers/home/RunsCard/index.tsx
src/containers/home/SequenceCard/index.tsx
src/containers/home/SubjectCard/index.tsx
src/containers/lims/LIMSTable/index.tsx
src/containers/metadata/MetadataTable/index.tsx
src/containers/runs/RunOverviewTable/index.tsx
src/containers/s3/S3DataTable/index.tsx
src/containers/subjects/FileViewer/index.tsx
src/containers/subjects/IGV/index.tsx
src/containers/subjects/SampleInformationTable/index.tsx
src/containers/subjects/SubjectListTable/index.tsx
src/containers/subjects/SubjectOverviewTable/index.tsx
src/containers/subjects/SubjectRNASumLaunch/index.tsx
src/providers/ToastProvider/index.tsx

- Update toast component to pass `show()` function instead of `refs` on useContext
- IGV init component to refetchOnMount

Patch Issue #166 - Patch Toast Notification and IGV

---

buildspec.yml
package.json

* Sigh :/
* ditto https://github.com/umccr/infrastructure/pull/265
Related #177

Reverted to Nodejs 14 again!

---

src/components/DataTableWrapper/index.css
src/containers/metadata/MetadataTable/index.tsx
src/containers/subjects/SubjectListTable/index.tsx
src/pages/subjects/SubjectTablePage/index.tsx

- Add Search Bar in Subject Page
- Update loading animation
- CSS styling
Closes #179

#179 - SearchBar for Subject Page and Minor CSS

---

package.json
src/pages/SignInPage/index.tsx
yarn.lock

Release 2.0rc1

---

package.json
src/pages/SignInPage/index.tsx
start.sh
yarn.lock

* Made fallback to default static image if Unsplash fail
* Upgraded with unsplash-js SDK for newer API
* Improved photo credits and back linking
* Unsplash source API is deprecated
https://changelog.unsplash.com/deprecations/2021/11/25/source-deprecation.html

Fixed Login page using new Unsplash API

---

src/pages/SignInPage/index.tsx

* Added progress bar for UX easing
* Made lazy load default static image as late as possible

Improved UX Easing when handling Unsplash API

---

src/pages/SignInPage/index.tsx

Release 2.0rc3

---

src/api/gds.ts
src/api/s3.ts
src/components/DataActionButton/index.tsx
src/containers/gds/GDSDataTable/index.tsx
src/containers/s3/S3DataTable/index.tsx
src/containers/subjects/AnalysisResultTable/index.tsx
src/containers/utils/TokenDialog/index.tsx

Bug Fixes: Date && Cache

---

src/components/JSONToTable/index.tsx
src/containers/subjects/SubjectGPLLaunch/index.tsx

V1 has switched to GDS in previous PR. Updating in V2
Fix issue #204
Ref: [PR#143](https://github.com/umccr/data-portal-client/pull/143/files)

Change GPL Check from S3 to GDS

---

src/components/JSONToTable/index.tsx
src/containers/subjects/SubjectGPLLaunch/index.tsx

Fix https://github.com/umccr/data-portal-client/pull/205 for prod

Change GPL Check from S3 to GDS (#205)

---

src/components/DataActionButton/index.tsx
src/containers/subjects/IGV/LoadSubjectDataButton.tsx
src/containers/subjects/IGV/index.tsx
src/containers/subjects/IGV/utils.ts

- reconfigure API fetching for presignedURL
- isError fix
Fix #208

Misconfigured API

---

src/components/CircularLoaderWithText/index.tsx
src/components/DataActionButton/index.tsx
src/components/DataSearchFilterButton/index.tsx
src/containers/gds/GDSDataTable/index.tsx
src/containers/home/LimsCard/index.tsx
src/containers/home/MetadataCard/index.tsx
src/containers/home/RunsCard/index.tsx
src/containers/home/SequenceCard/index.tsx
src/containers/home/SubjectCard/index.tsx
src/containers/s3/S3DataTable/index.tsx
src/containers/subjects/AnalysisResultTable/index.tsx

- CSS update
- Improve helper text
Fix #200 
cc: @victorskl

Text and CSS Update

---

src/components/CircularLoaderWithText/index.tsx
src/components/DataActionButton/index.tsx
src/components/DataSearchFilterButton/index.tsx
src/containers/gds/GDSDataTable/index.tsx
src/containers/home/LimsCard/index.tsx
src/containers/home/MetadataCard/index.tsx
src/containers/home/RunsCard/index.tsx
src/containers/home/SequenceCard/index.tsx
src/containers/home/SubjectCard/index.tsx
src/containers/s3/S3DataTable/index.tsx
src/containers/subjects/AnalysisResultTable/index.tsx
src/containers/subjects/IGV/LoadSubjectDataButton.tsx
src/containers/subjects/IGV/index.tsx
src/containers/subjects/IGV/utils.ts

Fix for staging:
- [Issue #208](https://github.com/umccr/data-portal-client/issues/208) (Misconfigured API) in [PR #209 ](https://github.com/umccr/data-portal-client/pull/209)
- [Issue #203](https://github.com/umccr/data-portal-client/issues/203) (Auto close loading component when complete) in [PR #210 ](https://github.com/umccr/data-portal-client/pull/210)
- [Issue #200](https://github.com/umccr/data-portal-client/issues/200) (CSS and Helper text update) in [PR #211 ](https://github.com/umccr/data-portal-client/pull/211)

[STG] API Reconfigure and CSS Updates

---

src/components/CircularLoaderWithText/index.tsx
src/components/DataActionButton/index.tsx
src/components/DataSearchFilterButton/index.tsx
src/containers/gds/GDSDataTable/index.tsx
src/containers/home/LimsCard/index.tsx
src/containers/home/MetadataCard/index.tsx
src/containers/home/RunsCard/index.tsx
src/containers/home/SequenceCard/index.tsx
src/containers/home/SubjectCard/index.tsx
src/containers/s3/S3DataTable/index.tsx
src/containers/subjects/AnalysisResultTable/index.tsx
src/containers/subjects/IGV/LoadSubjectDataButton.tsx
src/containers/subjects/IGV/index.tsx
src/containers/subjects/IGV/utils.ts

Fix for prod:
- [Issue #208](https://github.com/umccr/data-portal-client/issues/208) (Misconfigured API) in [PR #209 ](https://github.com/umccr/data-portal-client/pull/209)
- [Issue #203](https://github.com/umccr/data-portal-client/issues/203) (Auto close loading component when complete) in [PR #210 ](https://github.com/umccr/data-portal-client/pull/210)
- [Issue #200](https://github.com/umccr/data-portal-client/issues/200) (CSS and Helper text update) in [PR #211 ](https://github.com/umccr/data-portal-client/pull/211)

[MAIN] API Reconfigure and CSS Updates

---

package.json
yarn.lock

* Bumped next version 2.1.0-rc.1
* Upgraded Vite 4.0
https://vitejs.dev/blog/announcing-vite4.html

Bumped version and dependencies

---

package.json
src/api/gds.ts
src/api/lims.ts
src/api/metadata.ts
src/api/run.ts
src/api/s3.ts
src/api/sequence.ts
src/api/subject.ts
src/components/DataActionButton/index.tsx
src/containers/subjects/IGV/utils.ts
src/containers/subjects/SubjectGPLLaunch/index.tsx
src/containers/subjects/SubjectRNASumLaunch/index.tsx
yarn.lock

* Fixed breaking changes
https://github.com/aws-amplify/amplify-js/tree/aws-amplify%405.0.11#notice

Upgraded Amplify 5

---

src/api/gds.ts
src/api/s3.ts
src/components/DataActionButton/index.tsx
src/containers/subjects/IGV/LoadCustomTrackDataButton.tsx
src/containers/subjects/IGV/LoadSubjectDataButton.tsx
src/containers/subjects/IGV/index.tsx
src/containers/subjects/IGV/utils.ts

- Custom load now support load from GDS (used to only  support S3)
- Change UI to accept URI instead of keys as an input
- Add some validation check if URI is valid before confirm of adding it to IGV. [UPDATE] Only available for GDS object
fix #217

Enhance IGV.js Custom Path Load

---

src/components/DataActionButton/index.tsx

Update Copy Key/Path to URI

---

src/components/CircularLoaderWithText/index.tsx
src/components/DataSearchFilterButton/index.tsx
src/components/FilePreviewButton/index.tsx
src/components/ViewPresignedUrl/index.css
src/components/ViewPresignedUrl/index.tsx

- Upgrade on TSV/CSV file previewer
Data taken from [UMCCR/NGS_Utils](https://github.com/umccr/NGS_Utils/blob/master/ngs_utils/reference_data/key_genes/umccr_cancer_genes.latest.tsv)
Fix #180

Improved File Viewer

---

src/api/gds.ts
src/components/FilePreviewButton/index.tsx
src/components/GeneratePresignedDialog/index.tsx

Request inline presign for GDS

---

src/api/subject.ts
src/containers/subjects/AnalysisResultTable/index.tsx
src/containers/subjects/SampleInformationTable/index.tsx
src/containers/subjects/SubjectGPLLaunch/index.tsx
src/containers/subjects/SubjectOverviewTable/index.tsx
src/containers/subjects/SubjectRNASumLaunch/aws.ts
src/containers/subjects/SubjectRNASumLaunch/index.tsx

-  The main attempt for this PR is for RNAsum refactor to use lambda invoke (Fix #232 )
- Enforcing the subject API types in the RNAsum caused a knock down effect on other files. Which explain why many files are touched in this PR
Other Improvement
- Confirm Dialog for all triggering workflows for RNAsum and GPL
Pending PR: #231 (Some variable relies on this PR)

RNAsum Trigger Refactor && Other Refactors

---

package.json
src/components/LaunchRNAsumReport.tsx
src/config.js
yarn.lock

Followup changes from https://github.com/umccr/data-portal-apis/pull/560
Migrate `/manops` API call to Lambda Invoke

Divert API to lambda Invoke for RNAsum

---

src/api/pairing.ts
src/containers/subjects/SubjectWGSTNLaunch/index.tsx

* See upstream changes for somatic+germline input output changes
https://github.com/umccr/data-portal-apis/pull/572

Updated tumor normal trigger pairing payload

---

src/containers/subjects/SubjectFeatureTable/index.tsx
src/main.css
src/pages/subjects/SubjectOverviewPage/index.tsx

* Adjusted Subject page layout with PrimeFlex Grid
Resolves #196

Reinstated Subject feature panel with circos plot

---

src/containers/subjects/AnalysisResultTable/index.tsx

Added TSO tsv output in Subject analysis summary panel

---

src/containers/Subject.js

[V1] Added TSO tsv output in Subject analysis summary panel

---

src/app.css
src/components/CircularLoaderWithText/index.tsx
src/components/DataTableWrapper/index.tsx
src/containers/gds/GDSDataTable/index.tsx
src/containers/metadata/MetadataTable/index.tsx
src/containers/s3/S3DataTable/index.tsx
src/containers/subjects/FileViewer/index.tsx
src/containers/subjects/IGV/LoadCustomTrackDataButton.tsx
src/containers/subjects/IGV/LoadSubjectDataButton.tsx
src/containers/subjects/IGV/index.tsx
src/containers/subjects/SampleInformationTable/index.tsx
src/containers/subjects/SubjectGPLLaunch/index.tsx
src/containers/subjects/SubjectListTable/index.tsx
src/containers/subjects/SubjectRNASumLaunch/index.css
src/containers/subjects/SubjectRNASumLaunch/index.tsx
src/containers/subjects/SubjectWGSTNLaunch/index.tsx
src/layouts/MenuBar/index.css
src/layouts/MenuBar/index.tsx
src/main.css
src/pages/LIMS/index.tsx

* Prepared the basis for multi themes switching
* Improved text and typography
* Improved Launch Pad flow and IGV dialogs
* Harmonised metadata columns across views

Adjusted round 1 of various UI and UX tinkering

---

src/api/lims.ts
src/containers/lims/LIMSTable/index.tsx
src/containers/lims/LimsSideBar/index.tsx
src/containers/runs/RunSideBar/index.tsx
src/containers/subjects/SubjectSideBar/index.tsx
src/layouts/SideBar/index.css
src/layouts/SideBar/index.tsx
src/pages/Home/index.tsx
src/pages/runs/RunLIMSPage/index.tsx

* This build Filter component independent of target DataTable component. Filtering query parameter state is lifted to parent. i.e. using approach "lifting state up" https://react.dev/learn/sharing-state-between-components
* However. Due to complexity, this is still "quirky" with filtering state that pass-around. There is a bit of "props-vs-state" React caveat; hurt my head a little.
* Also. Using "Set" struct might be better for bagging/collecting filtering params. Instead of "List". Order doesn't matter in this case. But, need to be set of keys.
* It could be couple ways to improve this. I will try "keep closer, together" approach, next. Hook useState are better within local within the component. Need of Filtering SideBar view is just presentation aspect only. Doesn't need to be in …

Implemented initial approach for LIMS DataTable Filtering

---

src/App.tsx
src/api/run.ts
src/components/DataSearchFilterButton/index.tsx
src/components/search/PresetButton/index.css
src/components/search/PresetButton/index.tsx
src/components/search/PresetDataFactory/index.ts
src/containers/gds/GDSDataTable/index.tsx
src/containers/lims/LIMSTable/index.tsx
src/containers/runs/RunOverviewTable/index.tsx
src/containers/runs/RunSideBar/index.tsx
src/containers/s3/S3DataTable/index.tsx
src/containers/subjects/SampleInformationTable/index.tsx
src/containers/subjects/SubjectWGSTNLaunch/index.tsx
src/layouts/MenuBar/index.tsx
src/pages/runs/RunDataPage/index.tsx
src/pages/runs/RunLIMSPage/index.tsx
src/pages/runs/RunOverviewPage/index.tsx
src/pages/subjects/SubjectDataPage/index.tsx
src/routes/runs/index.tsx

* Improved mainly focus around Run view
* Re-introduced Chip filter buttons for GDS and S3 DataTable
* Hide few routes, views and menu navigation that are needing
more time to rethink better UI/UX flow
* Switched to Bootstrap theme

Adjusted round 2 of various UI and UX tinkering

---

src/components/skel/FeatureSkeleton/index.tsx
src/components/skel/OverviewSkeleton/index.tsx
src/components/skel/TableSkeleton/index.tsx
src/containers/subjects/SampleInformationTable/index.tsx
src/containers/subjects/SubjectFeatureTable/index.css
src/containers/subjects/SubjectFeatureTable/index.tsx
src/containers/subjects/SubjectOverviewTable/index.tsx
src/containers/subjects/SubjectWGSTNLaunch/index.tsx

* Added filename caption to Circos plot Feature panel
* Minor typo improvement

Implemented Skeleton loader components

---

src/components/GDSActionMenuButton.js
src/components/PreviewActionButton.tsx
src/containers/Run.js
src/containers/Subject.js

[V1] Fixed GDS PreSigned URL with inline opening in Browser new tab

---

package.json
yarn.lock

[V1] Bumped dependencies

---

src/components/search/PresetDataFactory/index.ts
src/containers/lims/LIMSTable/index.tsx
src/containers/metadata/MetadataTable/index.tsx
src/containers/subjects/SampleInformationTable/index.tsx

* Made some minor very desirable UX adjustment
* Left align Sample Info table by default
* Table that retained its cell structure when copy & paste

Added TSO json.gz to predefined search filter i.e. preset chip collection

---

package.json
src/components/GDSActionMenuButton.js
src/components/PreviewActionButton.tsx
src/containers/Run.js
src/containers/Subject.js
yarn.lock

* Fixes for Portal v1 UI counterpart 
* ditto #258 for detail comment

[V1] Fixed Generate Download Link

---

package.json
src/components/FilePreviewButton/index.tsx
src/components/GeneratePresignedDialog/index.tsx
src/components/ViewPresignedUrl/index.tsx
src/components/search/PresetDataFactory/index.ts
src/containers/lims/LIMSTable/index.tsx
src/containers/metadata/MetadataTable/index.tsx
src/containers/subjects/AnalysisResultTable/index.tsx
src/containers/subjects/SampleInformationTable/index.tsx
yarn.lock

Testing in Dev looking good. Promoting the patch fix to Staging.

[STG] Fixed Generate Download Link

---

package.json
src/components/FilePreviewButton/index.tsx
src/components/GeneratePresignedDialog/index.tsx
src/components/ViewPresignedUrl/index.tsx
src/components/search/PresetDataFactory/index.ts
src/containers/lims/LIMSTable/index.tsx
src/containers/metadata/MetadataTable/index.tsx
src/containers/subjects/AnalysisResultTable/index.tsx
src/containers/subjects/SampleInformationTable/index.tsx
yarn.lock

Validation in Staging Portal is good. Got green light for PROD. Shipping.
---
Also contains related fixes (_battery included!_):
- Remove srcDoc from iframe that fix Preview button (related with PreSigned URL download mode)
- Allowed TSO `json.gz` to predefined search filter
- Allowed quick download icon for `vcf.gz` `.maf` in Analysis Result panel

[PROD] Fixed Generate Download Link

---

package.json
src/components/GDSActionMenuButton.js
src/components/PreviewActionButton.tsx
src/containers/Run.js
src/containers/Subject.js
yarn.lock

[V1] [PROD] Fixed Generate Download Link

---

src/api/gds.ts
src/api/s3.ts
src/components/FilePreviewButton/index.tsx
src/components/OpenInNewTab/index.tsx
src/components/ViewPresignedUrl/index.tsx
src/containers/utils/DataActionButton/index.tsx

- PDF viewer is working with `<iframe>` tag
- Add "Open In New Tab" on the data action button

Add PDF Viewer

---

package.json
yarn.lock

See
https://github.com/prettier/prettier/issues/15022
https://github.com/prettier/eslint-plugin-prettier/issues/562

Rolled back prettier

---

src/components/search/PresetDataFactory/index.ts
src/containers/subjects/AnalysisResultTable/index.tsx

* Allow view inline preview as well as open in new tab
* Also added chip fusion filter to Subject Data view
* Support both ICA v1 and bcBio pipelines output

Added WTS fusions report to Analysis Results summary panel

---

src/components/search/PresetDataFactory/index.ts
src/containers/subjects/AnalysisResultTable/index.tsx

* Also added germline vcf chip filter to Subject Data view

Added germline VCFs to Analysis Results summary panel

---

src/components/RestoreArchiveObjectDialog/index.tsx

Fix S3 Archival API

---

src/containers/subjects-launch/SubjectRNASumLaunch/index.tsx
src/containers/subjects/AnalysisResultTable/index.tsx

Fix CodeBuild [error](https://umccr.slack.com/archives/C7QC9N8G4/p1692668597166689)

Fix Discrepancy Variable Naming

---

src/containers/subjects-launch/SubjectRNASumLaunch/index.tsx

Fix [Failed CodeBuild](https://umccr.slack.com/archives/C7QC9N8G4/p1692670935652839)

Update Default Component Name for RNAsum trigger

---

package.json
src/App.js
src/containers/AppBar.js
src/index.js
yarn.lock

Quick show alert message moving to V2

Deprecation Alert

---

src/containers/subjects-launch/SubjectGPLLaunch/index.tsx
src/containers/subjects-launch/SubjectOncoanalyserLaunch/index.tsx
src/containers/subjects-launch/SubjectWTSStarAlignment/index.tsx
src/pages/subjects/SubjectLaunchPad/index.tsx

* Added warning message if navigate directly, somehow
* Fixed typo GPL

Disabled temporarily oncoanalyser from Launch Pad UI

---

package.json
yarn.lock

Release `2.2rc3` UI for Staging

Release 2.2rc3

---

README.md
buildspec.yml
package.json
src/App.js
yarn.lock

* Bump Nodejs 18
* Tuned content container padding

[V1] Bump version 1.1.3

---

README.md
buildspec.yml
package.json
src/App.js
src/containers/AppBar.js
src/index.js
yarn.lock

See https://github.com/umccr/data-portal-client/milestone/11?closed=1

Release 1.1.3

---

src/api/subject.ts
src/containers/subjects/AnalysisResultTable/index.tsx

Added new tab for `WGS (sash)`

Subject Overview for Sash Output

---

src/containers/subjects/AnalysisResultTable/index.tsx

- Add Alert message for WGS(sash) files
- fix BAM files display for sash

Alert Message

---

src/containers/subjects/AnalysisResultTable/index.tsx

Add quick S3 downloadable button (Ref [Slack Threads](https://umccr.slack.com/archives/CP356DDCH/p1707115362457349?thread_ts=1704942416.535389&cid=CP356DDCH))

Add Downloadable S3 Button

---

package.json
src/api/fastq.ts
src/api/gds.ts
src/api/lims.ts
src/api/metadata.ts
src/api/pairing.ts
src/api/run.ts
src/api/s3.ts
src/api/sequence.ts
src/api/subject.ts
src/containers/lims/LimsSideBar/index.tsx
yarn.lock

Fixing the filtering problem on lims page, which apparently is also related to the mutl-query params behaviour. 
Fix #323 , #322

Fix: Filter && Amplify Multi Param Query Behaviour 

---

src/containers/lims/LIMSTable/index.tsx
src/containers/lims/LimsSideBar/index.tsx

Fix:
1. when remove all filter params, click apply button will reset to default table
2. when click clear will clear all params and reset to default table
new clear button

Fix - apply filter reset function

---

src/containers/subjects/AnalysisResultTable/index.tsx

Draft to add portal run id in the analysis result for #324

Added portal run id beside filenames

---

src/api/subject.ts
src/containers/subjects/AnalysisResultTable/index.tsx

Add TSO500V2 tab in the analysis results panel.

Feature: add spot in the analysis results panel

---

eslint.config.mjs
src/api/s3.ts
src/components/OpenInIgvDialog/gds.ts
src/components/OpenInIgvDialog/index.tsx
src/components/OpenInIgvDialog/s3.ts
src/components/OpenInIgvDialog/utils.ts
src/containers/s3/S3DataTable/index.tsx
src/containers/subjects/AnalysisResultTable/index.tsx
src/containers/subjects/IGV/index.tsx
src/containers/subjects/IGV/utils.ts
src/containers/utils/DataActionButton/index.tsx

- `cttsov2` to enforce presigned mode when opening in IGV
- Some refactoring on IGV component 
Resolve #344

Feat: Allow IGV open in presigned mode in S3

---

src/api/s3.ts
src/components/search/PresetDataFactory/index.ts
src/containers/subjects/AnalysisResultTable/index.tsx

Improved Analysis Results panel WGS sash tab UX behaviours

---

eslint.config.mjs
package.json
src/api/s3.ts
src/components/OpenInIgvDialog/gds.ts
src/components/OpenInIgvDialog/index.tsx
src/components/OpenInIgvDialog/s3.ts
src/components/OpenInIgvDialog/utils.ts
src/components/search/PresetDataFactory/index.ts
src/containers/s3/S3DataTable/index.tsx
src/containers/subjects/AnalysisResultTable/index.tsx
src/containers/subjects/IGV/index.tsx
src/containers/subjects/IGV/utils.ts
src/containers/subjects/SubjectSideBar/index.tsx
src/containers/utils/DataActionButton/index.tsx
yarn.lock

Release `2.2.2-rc3` for Staging
So far so good with testing in dev, will make final testing in Staging. If all good, we are ready to ship to prod.

Release 2.2.2-rc3

---

src/pages/subjects/SubjectLaunchPad/index.tsx

Disabled GPL trigger from Launch Pad

---

package.json
yarn.lock

* Having issue with browser native selectable to datatable

Pinned primereact

---

package.json

UI 2.2.3 Staging

---

src/components/FilePreviewButton/index.tsx
src/containers/subjects/AnalysisResultTable/index.tsx

Enable preview function for cttsov2 files

enable preview for cttsov2 files

---

src/containers/gds/GDSDataTable/index.tsx
src/containers/subjects-launch/utils/ConfirmationDialog.tsx
src/containers/subjects/AnalysisResultTable/index.tsx
src/pages/runs/RunDataPage/index.tsx
src/pages/subjects/SubjectDataPage/index.tsx

* Added graceful data under migration message where appropriate
* Made S3 tab as default

Disabled user actionable items related to GDS and LaunchPad

---

src/api/subject.ts
src/components/FilePreviewButton/index.tsx
src/containers/subjects/AnalysisResultTable/index.tsx

* Portal will show (in-place of GDS) analysis results from newer
buckets. Both BYOB cache and Archive locations are supported.

Support analysis results from relocated buckets
