umccr/data-portal-client

- package.json
- yarn.lock
* Seem to something wrong with `2.7.5` module export. Build failed with:
`Cannot find module: 'igv'. Make sure this package is installed.`
> Rolled back igv.js version to `2.7.4`

- src/containers/IGV.tsx
- src/typings/index.d.ts
Better unmounting of IGV
Types for S3 data
Minor other fixes
> Allow variants to be selected as tracks

- buildspec.yml
- package.json
* On CodeBuild VM, src is none git checkout
* Might as well too late at this point if secrets detect
or audit failure when building client artifact. These
should be prevented before even PR get merges to main or
dev branches.
> Excluded pre-commit from yarn install prepare hook

- src/App.js
Specifying `Google` as the Identity Provider. This will allow to skip the `Sign In with your social account` page (which only has one button to press).
> Change SignIn function

- package.json
- src/components/PreviewActionButton.tsx
- src/containers/Subject.js
- yarn.lock
Added PresignedURL Preview button (beside on the `Action (Menu Icon)` button) in SubjectData (`GDS` and `S3`) and AnalysisResults Tabs. 
List of extension supported:
- png, jpg, jpeg
- html
- csv
- tsv
- md5sum
- txt
- JSON
- yaml
> Add file preview for PresignedUrl

- src/components/PreviewActionButton.tsx
- Image re-sizing to fit Dialog component
- Suspend all filetype preview **except** images and HTML (PNG, JPG, JPEG, HTML), due to `cors-origin-policy`
NOTE: It will be squashed merge (Ignore the lousy git commit messages 😉)
> Update preview button

- src/Routes.js
- src/containers/FileViewer.tsx
- src/containers/FileViewers.tsx
- src/containers/Home.js
- src/containers/Subject.js
- Added new route `/files/{subjectId}` for png preview files from S3
- Available preview options (with RegExr): 
```
{ name: 'GPL - all', regexKey: 'gridss_purple_linx/(.*)(.png$)' },
{ name: 'GPL - purple', regexKey: 'gridss_purple_linx/purple/(.*)(.png$)' },
{ name: 'GPL - linx', regexKey: 'gridss_purple_linx/linx/(.*)(.png$)' },
{ name: 'UMCCRISED - all', regexKey: 'umccrised/(.*)(.png$)' },
```
- Added button to link to this routes via `lims-table` and `subject-page`
> Add`.png` file previewer page

- src/routes/index.tsx
Explicit `If-else` routing for non-authenticated user instead of redirect.
> Auth Refactor Routing

- src/components/DataActionButton/index.tsx
Essentially, the `OpenIGVDesktop` component/button must also return the component and close the dialog (to enable retries).
> patch issue #166 - Open IGV Desktop

- src/api/gds.ts
- src/api/s3.ts
- src/components/DataActionButton/index.tsx
- src/containers/gds/GDSDataTable/index.tsx
- src/containers/s3/S3DataTable/index.tsx
- src/containers/subjects/AnalysisResultTable/index.tsx
- src/containers/utils/TokenDialog/index.tsx
- Identify and Fix on Date parsing Bug
Problem: GDS uses `time_modified` while S3 uses `last_modified_date`, previous attempt did not distinguish between this fields and uses the same key which causes the bug for undefined and led to date to show current date.
Solution: Having a seperate function/component to view GDS and S3 date from API response. Additionally all typed Backend response are also added to respective GDS/S3 Rows.
- Added more dependancy for presignedUrl fetching 
Problem: Fetching dependancy did not rely on objectId as it rely to refetch as component is remounting when navigate to preosignedUrl component. This might hit edge case when user had been idle too long but data still exist from previous data.
Solution: Added S3/GDS ID and the type for dependancy when fetching …
> Bug Fixes: Date && Cache

- src/components/DataActionButton/index.tsx
When file is loaded to IGV desktop:
- Cancel loading component
- Alert `success` on the completion
Fix #203 
cc: @victorskl
> Disable loading component

- src/containers/IGV.tsx
* Htsget-rs ID namespace uses without .bam or .vcf.gz extension
> Fixed Portal v1 IGV.js loading track support for htsget-rs ID style

- src/components/ViewPresignedUrl/index.tsx
Since we had some trouble on `Content-Type` from ICA presigned URL. As I mentioned, we could download the HTML tags and pass it to `<iframe/>`. Pretty much what is expected from an ICA presigned URL (see screenshot).
Just a proposal 😉
> HTML Presigned URL Component Proposal

- src/containers/subjects/SubjectRNASumLaunch/index.tsx
* Pipeline automation will use "latest greatest" strategy
i.e. it uses "recent" WTS library and its most recent
transcriptome run output automatically
* Related #219
https://github.com/umccr/data-portal-apis/issues/547
> Allowed RNAsum trigger on multiple transcriptome output

- src/api/gds.ts
- src/api/s3.ts
- src/containers/subjects/AnalysisResultTable/index.tsx
- src/providers/ToastProvider/index.tsx
* Going ford UI/UX: Opening a html Report in new inline browser tab
shall be our default option
* Everything else is secondary options such as download, preview, ...
* Adjusted Toast message to screen Left Bottom position, no opacity and,
this should be default message location. As that corner will be
our best less crowded screen estate.
* Resolves #162
> Implemented open Report in inline browser tab

- package.json
- src/components/FilePreviewButton/index.tsx
- src/components/GeneratePresignedDialog/index.tsx
- src/components/ViewPresignedUrl/index.tsx
- src/containers/subjects/AnalysisResultTable/index.tsx
- yarn.lock
* Improved PreSigned API call implementation by clear separation between
* By default, without API Config override, use attachment download mode
* Any inline rendering need, must API call with providing headers --
Content-Disposition
Content-Type
* See https://github.com/umccr/data-portal-apis/pull/585
* Related #257
* Added mime package for determining content type
* Added Analysis Results download icon support for gz, maf formats
> Fixed Generate Download Link

- src/components/ViewPresignedUrl/index.tsx
It turns out using `srcDoc` from `<iframe/>` need somehow isolation (based from quick googling), as with current implementation clicking a link from the html previewer will redirect to the parent link. Reproducible by clicking a link from the HTML previewer (say from a `multiqc.html`) in `stg` or `prod`.
Since https://github.com/umccr/data-portal-apis/pull/581 has been done, will reimplement this to the original solution.
> Remove `srcDoc` from `<iframe/>`

- src/api/utils.ts
- src/components/OpenInIgvDialog/index.tsx
- src/containers/subjects/AnalysisResultTable/index.tsx
- src/containers/subjects/IGV/genomes.ts
- src/containers/subjects/IGV/index.tsx
- src/containers/subjects/IGV/utils.ts
- src/pages/subjects/SubjectDataPage/index.tsx
- Added format of igv name parameter to `{subjectId}_{type}_{libraryId}_filename.bam` for both IGV local and js
- Update reference genome for IGV js
Ref: [Slack - Threads](https://umccr.slack.com/archives/CP356DDCH/p1706583808733149)
> Extensive IGV Name Parameter

- src/containers/subjects/AnalysisResultTable/index.tsx
Fix for #327  PortalRunId column display issue.
cttsov2 key has one more layer in key attribute
```
key: "byob-icav2/development/analysis/cttsov2/202406214ff0a712/Logs_Intermediates/DragenCaller/L2400165/L2400165_tumor.bam"
```
noraml sash object key:
```
key:"analysis_data/SBJ04375/sash/2023102824ce1c40/L2301202_L2301201/SBJ04375_MDX230471/smlv_somatic/filter/MDX230471.annotations.pass.vcf.gz
```
Add one `check function: getPortalRunIdFromS3Key` when retrieve portalRunId from s3 key. If the 4th layer didn't start with 8 digits, we will try next layer. 
It just have these two situation so far, either in 4th layer or 5th.
> hotfix for cttsov2 portalRunId

- src/containers/subjects/SubjectSideBar/index.tsx
Resolve #341 
Adding preventDefault fixes it, perhaps they change how onClick ordering/priority in the `ListBox` component
> Fix SideBar Menu Click Reload 

- src/containers/subjects/AnalysisResultTable/index.tsx
* When analysis results get moved into the archive bucket, workflow type
are dropped from the mid-path.
> Handled analysis results from archive bucket
